### ISSUE TITLE
Fail to find keywords

### ISSUE THREAD

**Issue by Yinghao-Li** [thongyixuen/brat#11]
I tried to label something with keywords, but when I clicked the "execute" button, the page jumped back to the start page and there's no label given

![image](https://user-images.githubusercontent.com/39107015/102515204-71c6fd00-405b-11eb-8fd0-129143f524f1.png)

**Comment by leonard-thong** [comment]
Hi Yinghao, I am unable to reproduce this error. May I know if you have selected the match case and scope?

**Comment by Yinghao-Li** [comment]
It seems that the reason is the extended response time we encountered last week.

**Comment by leonard-thong** [comment]
I see, I will go ahead to implement the warning for the case when you choose all collections.
