### ISSUE TITLE
Creating Account

### ISSUE THREAD

**Issue by Yinghao-Li** [thongyixuen/brat#12]
I did not find where I can create an account.

**Comment by dreamyang-liu** [comment]
Hi Yinghao,

According to brat official document, User and password settings are specific to the server configuration. If users need a new login or have forgotten your password, they should contact the administrator of your brat installation.

If you really want this feature, we can create one interface for it.

**Comment by Yinghao-Li** [comment]
I was just curious why there's a "log in" button but no account creating function. Having an account creation function seems to be helpful for user-oriented functions such as user-specific directory tree, etc. But it is just an improvement not necessary right now. It would be better to solve other issues first.

**Comment by leonard-thong** [comment]
I see, I will go ahead to implement the warning for the case when you choose all collections and close this issue.
